
{'date': 'Sun Jul 04 2021 22:26:02.577 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 9
  PERSONAGEM ANDANDO= "https://i.imgur.com/Jo5Ho94.png"
              ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 05 2021 18:00:16.806 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 25
  self.personagem = Elemento (img = FOLHA, cena = self.fundo, x= self.x2, y= self.y2, h=80, w= 80
                                                                                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jul 05 2021 18:01:25.572 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 44
    inicial().vai()
  module <module> line 25
    self.personagem = Elemento(img = FOLHA, cena = self.fundo, x=self.x1, y=self.y1, h=100, w=100)
NameError: name 'FOLHA' is not defined
'''},
{'date': 'Mon Jul 05 2021 18:09:40.659 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 23
  self.personagem = Elemento(img = FOLHA, cena = self.fundo, x=self.x1, y=self.y1, h=80, w=80)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 05 2021 18:10:00.315 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 23
  self.personagem = Elemento(img = FOLHA, cena = self.fundo, x=self.x1, y=self.y1, h=80, w=80)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jul 05 2021 18:14:29.293 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 50
    inicial().vai()
  module <module> line 22
    self.personagem = Elemento(img = PERSONAGEM, cena = self.fundo, x=self.x1, y=self.y1, h=100, w=100)
AttributeError: 'inicial' object has no attribute 'x1'
'''},
{'date': 'Mon Jul 12 2021 18:03:34.672 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 44
    inicial().vai()
  module <module> line 22
    self.folha()
AttributeError: 'inicial' object has no attribute 'folha'
'''},
{'date': 'Mon Jul 12 2021 18:03:52.853 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 43
    inicial().vai()
  module <module> line 22
    self.personagem = Elemento(img = PERSONAGEM, cena = self.fundo, x=self.x1, y=self.y1, h=100, w=100)
AttributeError: 'inicial' object has no attribute 'x1'
'''},
{'date': 'Mon Aug 16 2021 17:23:11.775 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 30
  FUNDO_CENA12 =
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 16 2021 17:26:40.944 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 30
  FUNDO_CENA12 =
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 16 2021 17:26:47.867 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 30
  FUNDO_CENA12 =
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 16 2021 17:27:09.418 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 30
  FUNDO_CENA12 =
                 ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 16 2021 17:28:59.281 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 81
  self.persona1 = Elemento(PERSONAGEM1, h=170 , w=190, x=self.x, y=self.y) # cria Elemento
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Aug 30 2021 17:43:01.770 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 159
    teste()
  module <module> line 47
    bonequinha = Persona_control( fundo) 
  module <module> line 100
    self.persona = Elemento(PERSONAGEM, h=170 , w=190, x=self.x, y=self.y) # cria Elemento 
NameError: name 'PERSONAGEM' is not defined
'''},
{'date': 'Mon Aug 30 2021 17:43:14.607 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 159
    teste()
  module <module> line 47
    bonequinha = Persona_control( fundo) 
  module <module> line 100
    self.persona = Elemento(PERSONAGEM, h=170 , w=190, x=self.x, y=self.y) # cria Elemento 
NameError: name 'PERSONAGEM' is not defined
'''},
{'date': 'Mon Aug 30 2021 17:44:19.893 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 160
    teste()
  module <module> line 47
    bonequinha = Persona_control( fundo) 
  module <module> line 101
    self.persona = Elemento(PERSONAGEM, h=170 , w=190, x=self.x, y=self.y) # cria Elemento 
NameError: name 'PERSONAGEM' is not defined
'''},
{'date': 'Mon Aug 30 2021 18:06:00.568 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 134
  if (self.persona.x > 0 && self.persona < 1350):
                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 30 2021 18:06:11.454 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 134
  if (self.persona.x > 0 && self.persona.x < 1350):
                           ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Sep 14 2021 20:10:48.195 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 147
    teste()
  module <module> line 42
    bonequinha = Persona_control( fundo) 
  module <module> line 58
    self.c13 = Cena(FUNDO_CENA3)
NameError: name 'FUNDO_CENA3' is not defined
'''},
{'date': 'Mon Sep 20 2021 17:15:32.46 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 73
  self.x = 10 # valor pré-estabelecido do x
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 20 2021 17:16:53.474 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 72
  def __init__(self, nome_do_fundo):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 20 2021 17:17:19.719 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 288
    jogo.teste()
TypeError: teste() takes 0 positional argument but more were given
'''},
{'date': 'Mon Sep 20 2021 17:18:03.29 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 288
    jogo.teste()
TypeError: teste() takes 0 positional argument but more were given
'''},
{'date': 'Mon Sep 20 2021 17:18:18.881 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 287
    jogo.teste()
TypeError: teste() takes 0 positional argument but more were given
'''},
{'date': 'Mon Sep 20 2021 17:20:11.82 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 100
  def verifica_proximidade(self, item_x, item_y):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 20 2021 17:22:45.382 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 281
    jogo.cena1()
AttributeError: 'cenas' object has no attribute 'cena1'
'''},
{'date': 'Mon Sep 20 2021 17:23:37.972 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 281
    jogo.cena1()
AttributeError: 'cenas' object has no attribute 'cena1'
'''},